name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:        
      - name: Install and Build 🔧 folder
        run: |
          npm install
          npm run deploy

   
